### ISSUE TITLE
Problem while burning the iso to a dvd

### ISSUE THREAD

**Issue by KarimGeiger** [benaryorg/benarydingOS#11]
When trying to burn the generated iso to a dvd it says "Failed to read from Sector '0'".

**Comment by benaryorg** [comment]
You _really_ tried that?!

Okay, thats something new for us….
We just tried using USBs

But @nilsding will help you, hes our hardware guru….

**Comment by nilsding** [comment]
```
>wasting a DVD with a ~500kB ISO
```

You, sir, are made of money.  
Anyway, I'll look further into that.

**Comment by benaryorg** [comment]
@nilsding What could be the Problem?

**Comment by Manawyrm** [comment]
![2014-01-29 20 36 34 hdr](https://f.cloud.github.com/assets/748791/2033438/f8d8cfba-891c-11e3-9bce-f529dff261fa.jpg)
Works perfectly. Picture attached ;)
I call Layer 8 problem ;)

**Comment by benaryorg** [comment]
Perfectly!
