### ISSUE TITLE
CPU Reset

### ISSUE THREAD

**Issue by benaryorg** [benaryorg/benarydingOS#5]
On Segment reload I get a CPU Reset

**Comment by benaryorg** [comment]
We need a fucking Programmer with experience!

**Comment by benaryorg** [comment]
Now working
Failure was that the uint64_t was only 16 bit of size instead of 64 bit (nilsdings fault, he took the darwin stdint.h)

**Comment by nilsding** [comment]
pretty much apple's fault if you ask me
